// Code generated by goctl. DO NOT EDIT.
package types

type GetUsersReq struct {
	Ids string `json:"ids"` // 多个用户,号隔开
}

type GetUsersResp struct {
	Users []UserInfo `json:"users"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResp struct {
	UserId string `json:"user_id"`
}

type UpdateUserReq struct {
	UserInfo
}

type UpdateUserResp struct {
}

type UserInfo struct {
	Id        string `json:"id"`
	Avatar    string `json:"avatar"`
	Nickname  string `json:"nickname"`
	Account   string `json:"account"`
	Password  string `json:"password"`
	Bio       string `json:"bio"`
	Gender    string `json:"gender"`
	Region    string `json:"region"`
	CreatedAt string `json:"created_at"`
}
