// Code generated by goctl. DO NOT EDIT.
package types

type CancellationReq struct {
	UserId string `json:"user_id"`
}

type Cancellationresp struct {
}

type CreatePostReq struct {
	Post
}

type CreatePostResp struct {
}

type DeleteReq struct {
	Id string `json:"post_id"`
}

type DeleteResp struct {
}

type GetUserPostsReq struct {
	UserId string `json:"user_id"`
}

type GetUserPostsResp struct {
	Posts []Post `json:"list"`
}

type GetUsersReq struct {
	Ids string `json:"ids"` // 多个用户,号隔开
}

type GetUsersResp struct {
	Users []UserInfo `json:"users"`
}

type InfoReq struct {
	Id string `json:"post_id"`
}

type InfoResp struct {
	Post
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type Post struct {
	Id        string `json:"id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	UserId    string `json:"user_id"`
	Views     int64  `json:"views"`
	Likes     int64  `json:"likes"`
	Comments  int64  `json:"comments"`
	Shares    int64  `json:"shares"`
	Collects  int64  `json:"collects"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResp struct {
	UserId string `json:"user_id"`
}

type UpdatePostReq struct {
	Post
}

type UpdatePostResp struct {
}

type UpdateUserReq struct {
	UserInfo
}

type UpdateUserResp struct {
}

type UserInfo struct {
	Id        string `json:"id"`
	Avatar    string `json:"avatar"`
	Nickname  string `json:"nickname"`
	Account   string `json:"account"`
	Password  string `json:"password"`
	Bio       string `json:"bio"`
	Gender    int64  `json:"gender"`
	Region    string `json:"region"`
	CreatedAt string `json:"created_at"`
}
