// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.6.1
// source: like.proto

package like

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LikeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"` // 用户ID
	PostId        int64                  `protobuf:"varint,2,opt,name=PostId,proto3" json:"PostId,omitempty"` // 推文ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeReq) Reset() {
	*x = LikeReq{}
	mi := &file_like_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeReq) ProtoMessage() {}

func (x *LikeReq) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeReq.ProtoReflect.Descriptor instead.
func (*LikeReq) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{0}
}

func (x *LikeReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LikeReq) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type LikeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeResp) Reset() {
	*x = LikeResp{}
	mi := &file_like_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeResp) ProtoMessage() {}

func (x *LikeResp) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeResp.ProtoReflect.Descriptor instead.
func (*LikeResp) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{1}
}

type UnlikeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"` // 用户ID
	PostId        int64                  `protobuf:"varint,2,opt,name=PostId,proto3" json:"PostId,omitempty"` // 推文ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeReq) Reset() {
	*x = UnlikeReq{}
	mi := &file_like_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeReq) ProtoMessage() {}

func (x *UnlikeReq) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeReq.ProtoReflect.Descriptor instead.
func (*UnlikeReq) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{2}
}

func (x *UnlikeReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnlikeReq) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type UnlikeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeResp) Reset() {
	*x = UnlikeResp{}
	mi := &file_like_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeResp) ProtoMessage() {}

func (x *UnlikeResp) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeResp.ProtoReflect.Descriptor instead.
func (*UnlikeResp) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{3}
}

type GetLikersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"` // 推文ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLikersReq) Reset() {
	*x = GetLikersReq{}
	mi := &file_like_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLikersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikersReq) ProtoMessage() {}

func (x *GetLikersReq) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikersReq.ProtoReflect.Descriptor instead.
func (*GetLikersReq) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{4}
}

func (x *GetLikersReq) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type GetLikersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Infos         []*LikersInfo          `protobuf:"bytes,1,rep,name=Infos,proto3" json:"Infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLikersResp) Reset() {
	*x = GetLikersResp{}
	mi := &file_like_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLikersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikersResp) ProtoMessage() {}

func (x *GetLikersResp) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikersResp.ProtoReflect.Descriptor instead.
func (*GetLikersResp) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{5}
}

func (x *GetLikersResp) GetInfos() []*LikersInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

type LikersInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PostId        int64                  `protobuf:"varint,2,opt,name=PostId,proto3" json:"PostId,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikersInfo) Reset() {
	*x = LikersInfo{}
	mi := &file_like_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikersInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikersInfo) ProtoMessage() {}

func (x *LikersInfo) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikersInfo.ProtoReflect.Descriptor instead.
func (*LikersInfo) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{6}
}

func (x *LikersInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LikersInfo) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *LikersInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *LikersInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *LikersInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_like_proto protoreflect.FileDescriptor

const file_like_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"like.proto\x12\x04like\"9\n" +
	"\aLikeReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x16\n" +
	"\x06PostId\x18\x02 \x01(\x03R\x06PostId\"\n" +
	"\n" +
	"\bLikeResp\";\n" +
	"\tUnlikeReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x16\n" +
	"\x06PostId\x18\x02 \x01(\x03R\x06PostId\"\f\n" +
	"\n" +
	"UnlikeResp\"&\n" +
	"\fGetLikersReq\x12\x16\n" +
	"\x06PostId\x18\x01 \x01(\x03R\x06PostId\"7\n" +
	"\rGetLikersResp\x12&\n" +
	"\x05Infos\x18\x01 \x03(\v2\x10.like.LikersInfoR\x05Infos\"\x8e\x01\n" +
	"\n" +
	"LikersInfo\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x16\n" +
	"\x06PostId\x18\x02 \x01(\x03R\x06PostId\x12\x1a\n" +
	"\bNickname\x18\x03 \x01(\tR\bNickname\x12\x16\n" +
	"\x06Avatar\x18\x04 \x01(\tR\x06Avatar\x12\x1c\n" +
	"\tCreatedAt\x18\x05 \x01(\x03R\tCreatedAt2\x90\x01\n" +
	"\x04Like\x12%\n" +
	"\x04Like\x12\r.like.LikeReq\x1a\x0e.like.LikeResp\x12+\n" +
	"\x06Unlike\x12\x0f.like.UnlikeReq\x1a\x10.like.UnlikeResp\x124\n" +
	"\tGetLikers\x12\x12.like.GetLikersReq\x1a\x13.like.GetLikersRespB\bZ\x06./likeb\x06proto3"

var (
	file_like_proto_rawDescOnce sync.Once
	file_like_proto_rawDescData []byte
)

func file_like_proto_rawDescGZIP() []byte {
	file_like_proto_rawDescOnce.Do(func() {
		file_like_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_like_proto_rawDesc), len(file_like_proto_rawDesc)))
	})
	return file_like_proto_rawDescData
}

var file_like_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_like_proto_goTypes = []any{
	(*LikeReq)(nil),       // 0: like.LikeReq
	(*LikeResp)(nil),      // 1: like.LikeResp
	(*UnlikeReq)(nil),     // 2: like.UnlikeReq
	(*UnlikeResp)(nil),    // 3: like.UnlikeResp
	(*GetLikersReq)(nil),  // 4: like.GetLikersReq
	(*GetLikersResp)(nil), // 5: like.GetLikersResp
	(*LikersInfo)(nil),    // 6: like.LikersInfo
}
var file_like_proto_depIdxs = []int32{
	6, // 0: like.GetLikersResp.Infos:type_name -> like.LikersInfo
	0, // 1: like.Like.Like:input_type -> like.LikeReq
	2, // 2: like.Like.Unlike:input_type -> like.UnlikeReq
	4, // 3: like.Like.GetLikers:input_type -> like.GetLikersReq
	1, // 4: like.Like.Like:output_type -> like.LikeResp
	3, // 5: like.Like.Unlike:output_type -> like.UnlikeResp
	5, // 6: like.Like.GetLikers:output_type -> like.GetLikersResp
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_like_proto_init() }
func file_like_proto_init() {
	if File_like_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_like_proto_rawDesc), len(file_like_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_like_proto_goTypes,
		DependencyIndexes: file_like_proto_depIdxs,
		MessageInfos:      file_like_proto_msgTypes,
	}.Build()
	File_like_proto = out.File
	file_like_proto_goTypes = nil
	file_like_proto_depIdxs = nil
}
