// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	posts "go-zero-demo/bff/internal/handler/posts"
	system "go-zero-demo/bff/internal/handler/system"
	user "go-zero-demo/bff/internal/handler/user"
	"go-zero-demo/bff/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	systemHandler := system.NewSystemHandler()
	systemHandler.Version = Version

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/version",
				Handler: systemHandler.VersionHandler,
			},
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: systemHandler.HealthHandler,
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/post/Info",
				Handler: posts.InfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/post/Update",
				Handler: posts.UpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/post/create",
				Handler: posts.CreatHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/post/delete",
				Handler: posts.DeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/post/getUserPosts",
				Handler: posts.GetUserPostsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1"),
		rest.WithTimeout(5000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/cancellation",
				Handler: user.CancellationHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/get",
				Handler: user.GetUsersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/update",
				Handler: user.UpdateUserHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1"),
		rest.WithTimeout(5000*time.Millisecond),
	)
}
