// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: like.proto

package server

import (
	"context"

	"go-zero-demo/like/internal/logic"
	"go-zero-demo/like/internal/svc"
	"go-zero-demo/like/like"
)

type LikeServer struct {
	svcCtx *svc.ServiceContext
	like.UnimplementedLikeServer
}

func NewLikeServer(svcCtx *svc.ServiceContext) *LikeServer {
	return &LikeServer{
		svcCtx: svcCtx,
	}
}

// 点赞
func (s *LikeServer) Like(ctx context.Context, in *like.LikeReq) (*like.LikeResp, error) {
	l := logic.NewLikeLogic(ctx, s.svcCtx)
	return l.Like(in)
}

// 取消点赞
func (s *LikeServer) Unlike(ctx context.Context, in *like.UnlikeReq) (*like.UnlikeResp, error) {
	l := logic.NewUnlikeLogic(ctx, s.svcCtx)
	return l.Unlike(in)
}

// 获取推文点赞列表
func (s *LikeServer) GetLikers(ctx context.Context, in *like.GetLikersReq) (*like.GetLikersResp, error) {
	l := logic.NewGetLikersLogic(ctx, s.svcCtx)
	return l.GetLikers(in)
}
