// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: like.proto

package likeclient

import (
	"context"

	"go-zero-demo/like/like"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetLikersReq  = like.GetLikersReq
	GetLikersResp = like.GetLikersResp
	LikeReq       = like.LikeReq
	LikeResp      = like.LikeResp
	LikersInfo    = like.LikersInfo
	UnlikeReq     = like.UnlikeReq
	UnlikeResp    = like.UnlikeResp

	Like interface {
		// 点赞
		Like(ctx context.Context, in *LikeReq, opts ...grpc.CallOption) (*LikeResp, error)
		// 取消点赞
		Unlike(ctx context.Context, in *UnlikeReq, opts ...grpc.CallOption) (*UnlikeResp, error)
		// 获取推文点赞列表
		GetLikers(ctx context.Context, in *GetLikersReq, opts ...grpc.CallOption) (*GetLikersResp, error)
	}

	defaultLike struct {
		cli zrpc.Client
	}
)

func NewLike(cli zrpc.Client) Like {
	return &defaultLike{
		cli: cli,
	}
}

// 点赞
func (m *defaultLike) Like(ctx context.Context, in *LikeReq, opts ...grpc.CallOption) (*LikeResp, error) {
	client := like.NewLikeClient(m.cli.Conn())
	return client.Like(ctx, in, opts...)
}

// 取消点赞
func (m *defaultLike) Unlike(ctx context.Context, in *UnlikeReq, opts ...grpc.CallOption) (*UnlikeResp, error) {
	client := like.NewLikeClient(m.cli.Conn())
	return client.Unlike(ctx, in, opts...)
}

// 获取推文点赞列表
func (m *defaultLike) GetLikers(ctx context.Context, in *GetLikersReq, opts ...grpc.CallOption) (*GetLikersResp, error) {
	client := like.NewLikeClient(m.cli.Conn())
	return client.GetLikers(ctx, in, opts...)
}
