// Code generated by goctl. DO NOT EDIT.
// Source: post.proto

package server

import (
	"context"

	"go-zero-demo/post/internal/logic"
	"go-zero-demo/post/internal/svc"
	"go-zero-demo/post/post"
)

type PostServer struct {
	svcCtx *svc.ServiceContext
	post.UnimplementedPostServer
}

func NewPostServer(svcCtx *svc.ServiceContext) *PostServer {
	return &PostServer{
		svcCtx: svcCtx,
	}
}

// 发表推文
func (s *PostServer) CreatePost(ctx context.Context, in *post.CreatePostReq) (*post.CreatePostResp, error) {
	l := logic.NewCreatePostLogic(ctx, s.svcCtx)
	return l.CreatePost(in)
}

// 更新推文
func (s *PostServer) UpdatePost(ctx context.Context, in *post.UpdatePostReq) (*post.UpdatePostResp, error) {
	l := logic.NewUpdatePostLogic(ctx, s.svcCtx)
	return l.UpdatePost(in)
}

// 删除推文
func (s *PostServer) DeletePost(ctx context.Context, in *post.DeletePostReq) (*post.DeletePostReq, error) {
	l := logic.NewDeletePostLogic(ctx, s.svcCtx)
	return l.DeletePost(in)
}

// 获取单条推文
func (s *PostServer) GetPost(ctx context.Context, in *post.GetPostReq) (*post.GetPostResp, error) {
	l := logic.NewGetPostLogic(ctx, s.svcCtx)
	return l.GetPost(in)
}

// 批量获取推文
func (s *PostServer) BatchPost(ctx context.Context, in *post.BatchPostReq) (*post.BatchPostResp, error) {
	l := logic.NewBatchPostLogic(ctx, s.svcCtx)
	return l.BatchPost(in)
}

// 用户用户推文列表
func (s *PostServer) GetUserPostList(ctx context.Context, in *post.GetUserPostListReq) (*post.GetUserPostListResp, error) {
	l := logic.NewGetUserPostListLogic(ctx, s.svcCtx)
	return l.GetUserPostList(in)
}
